### ISSUE TITLE
New Commit uses unavailable docker images - Aarch64 Question too

### ISSUE THREAD

**Issue by wbelhomsi** [MetisProtocol/metis-replica-node#33]
### What Git revision / release tag are you using?

Latest

### What is your hardware specification?

1 TB SSD 64 GB RAM 32 GB VCPU

### What Docker version are you using?

Docker version 20.10.23, build 7155243

### What Linux distribution are you using?

Linux 6.1.34-59.116.amzn2023.aarch64 aarch64

### Describe what the problem is?

Is it possible to get aarch64 builds for the images provided please

```
image with reference ericlee42/metis:dtl-3 was found but does not match the specified platform: wanted linux/arm64/v8, actual: linux/amd64
```

Also the images put are not available, please fix the names

```
[+] Running 2/2
 ✘ l2geth Error                                                                                                                                                                                    1.1s
 ✘ l1dtl Error                                                                                                                                                                                     1.1s
Error response from daemon: pull access denied for ericlee/metis, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

found the images just under another name (e.g. ericlee42/metis:l2geth-5)

Also, 1 issue with the docker-compose https://github.com/MetisProtocol/metis-replica-node/blob/main/docker-compose-mainnet.yml#L33
should be `l1dtl`

**Comment by wbelhomsi** [comment]
actually found the images just add `42` to the name (e.g. `ericlee42/metis:l2geth-5`)

Have another issue though, you don't have aarch64. Would it be possible to build that?

**Comment by ericlee42** [comment]
Thanks, I will build one later

**Comment by ericlee42** [comment]
I can't build linux/arm64 for dtl.

a cpp library we're using is not supported by linux/arm64
