### ISSUE TITLE
`missing trie node:leveldb: not found` during sync

### ISSUE THREAD

**Issue by yorickdowne** [MetisProtocol/metis-replica-node#38]
### What Git revision / release tag are you using?

20240316

### What is your hardware specification?

6 CPU, 64 GiB RAM, 2 TB NVMe

### What Docker version are you using?

25.0.4

### What Linux distribution are you using?

Debian 12

### Describe what the problem is?

During sync, l2geth with `GCMODE=archive` will throw out some error logs, see below, starting with `missing trie node:leveldb: not found`. It does continue from there.

It may point at an issue in the code, at the very least an unhandled exception or an element that ought to be initialized (such as a DB) but isn't.

### If applicable, what are the logs from the server around the occurence of the problem?

 l2geth-1  | INFO [03-16|16:45:45.112] Imported new state entries               count=262  elapsed=134.154µs processed=17671421 pending=947   retry=0   duplicate=0 unexpected=0
l2geth-1  | INFO [03-16|16:45:45.385] Imported new state entries               count=518  elapsed=1.211ms   processed=17671939 pending=0     retry=0   duplicate=0 unexpected=0
l2geth-1  | INFO [03-16|16:45:45.385] Imported new block receipts              count=1    elapsed=124.117µs number=15289668 hash=1dfe6e…0be31d age=1h11m49s   size=2.35KiB
l2geth-1  | INFO [03-16|16:45:45.385] Committed new head block                 number=15289668 hash=1dfe6e…0be31d
l2geth-1  | INFO [03-16|16:45:45.430] Deallocated fast sync bloom              items=17671991 errorrate=0.000
l2geth-1  | ERROR[03-16|16:45:46.475] handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
l2geth-1  | WARN [03-16|16:45:46.501] Rolled back headers                      count=2048 header=15291273->15289225 fast=15289668->15289225 block=15289668->15289225
l2geth-1  | WARN [03-16|16:45:46.501] Synchronisation failed, retrying         err="element not found"
l2geth-1  | ERROR[03-16|16:45:46.505] missing trie node:leveldb: not found 
l2geth-1  | ERROR[03-16|16:45:46.506] goroutine 25 [running]:
l2geth-1  | runtime/debug.Stack()
l2geth-1  | 	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/trie.(*Database).node(0xc0004ec700, {0x11, 0xb7, 0x77, 0x11, 0xd6, 0xff, 0x30, 0x32, 0x72, ...})
l2geth-1  | 	/l2geth/trie/database.go:390 +0x28a
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/trie.(*Trie).resolveHash(0xc03f7c3878?, {0xc0000272c8?, 0xc00004da40?, 0x1031ea0?}, {0x0, 0x0, 0x0})
l2geth-1  | 	/l2geth/trie/trie.go:392 +0xda
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/trie.New({0x11, 0xb7, 0x77, 0x11, 0xd6, 0xff, 0x30, 0x32, 0x72, 0x0, ...}, ...)
l2geth-1  | 	/l2geth/trie/trie.go:71 +0xea
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/trie.NewSecure({0x11, 0xb7, 0x77, 0x11, 0xd6, 0xff, 0x30, 0x32, 0x72, 0x0, ...}, ...)
l2geth-1  | 	/l2geth/trie/secure_trie.go:58 +0x2f
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/core/state.(*cachingDB).OpenTrie(0x148772c?, {0x11, 0xb7, 0x77, 0x11, 0xd6, 0xff, 0x30, 0x32, 0x72, ...})
l2geth-1  | 	/l2geth/core/state/database.go:124 +0x29
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/core/state.New({0x11, 0xb7, 0x77, 0x11, 0xd6, 0xff, 0x30, 0x32, 0x72, 0x0, ...}, ...)
l2geth-1  | 	/l2geth/core/state/statedb.go:125 +0x49
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/core.(*BlockChain).StateAt(...)
l2geth-1  | 	/l2geth/core/blockchain.go:532
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/miner.(*worker).makeCurrent(0xc000dcc000, 0xc034c673b0, 0xc00ddcfd40)
l2geth-1  | 	/l2geth/miner/worker.go:790 +0x85
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/miner.(*worker).commitNewWork(0xc000dcc000, 0xc000027964?, 0x0)
l2geth-1  | 	/l2geth/miner/worker.go:1219 +0x7ae
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/miner.(*worker).mainLoop(0xc000dcc000)
l2geth-1  | 	/l2geth/miner/worker.go:486 +0xbfa
l2geth-1  | created by github.com/ethereum-optimism/optimism/l2geth/miner.newWorker in goroutine 1
l2geth-1  | 	/l2geth/miner/worker.go:251 +0x7a5
l2geth-1  |  
l2geth-1  | ERROR[03-16|16:45:46.506] Failed to create mining context          err="missing trie node 11b77711d6ff30327200ee7ef27a4815916b996f90727ee8e5d30e29b33c287f (path )"
l2geth-1  | INFO [03-16|16:45:48.915] Disabling direct-ancient mode            origin=15289668 ancient=15199731
l2geth-1  | INFO [03-16|16:45:49.044] Imported new state entries               count=259  elapsed=1.375µs   processed=17672198 pending=765   retry=0   duplicate=0 unexpected=0
l2geth-1  | INFO [03-16|16:45:49.062] Imported new block headers               count=192  elapsed=19.730ms  number=15289860 hash=fbb847…d2a66b age=1h2m5s
l2geth-1  | INFO [03-16|16:45:49.075] Imported new block headers               count=192  elapsed=11.707ms  number=15290052 hash=0d1562…242eaa age=53m21s
l2geth-1  | INFO [03-16|16:45:49.079] Imported new block receipts              count=4    elapsed=279.256µs number=15289672 hash=f86ea8…9a9212 age=1h11m19s   size=8.38KiB
l2geth-1  | INFO [03-16|16:45:49.093] Imported new block headers               count=192  elapsed=15.867ms  number=15290244 hash=992fc1…a6b7d7 age=46m51s
l2geth-1  | INFO [03-16|16:45:49.216] Imported new block headers               count=960  elapsed=82.792ms  number=15291204 hash=1aeb48…a83efb age=3m34s

**Comment by susuper** [comment]
I've got the same issue.

**Comment by ericlee42** [comment]
Hi, It's due to your l1dtl is not synced.

You can use the latest dtl snapshot and try again.
