### ISSUE TITLE
`GCMODE=archive` is mandatory for fresh sync

### ISSUE THREAD

**Issue by yorickdowne** [MetisProtocol/metis-replica-node#39]
### What Git revision / release tag are you using?

20240316

### What is your hardware specification?

6 CPU, 64 GiB RAM, 2 TB NVMe

### What Docker version are you using?

25.0.4

### What Linux distribution are you using?

Debian 12

### Describe what the problem is?

With `GCMODE=full`, l2geth will fail fresh sync. It'll fail with `panic: Refund counter below zero (gas: 15000 > refund: 8400)` and not recover from this, on restart it shows `missing trie node:leveldb: not found ` and fails.

This is a fresh sync, no snapshot, with l1dtl-4 and l2geth-5.
 
Adding `GCMODE=archive` to `l2geth.env` would be good. Alternatively, find and fix the issue that keeps `GCMODE=full` from working.

### If applicable, what are the logs from the server around the occurence of the problem?

INFO [03-16|15:00:49.635] Imported new chain segment               blocks=233   txs=233  mgas=71.414   elapsed=1.345s    mgasps=53.074   number=2312062 hash=ec0d4c…8d8448 age=1y11mo1w dirty=179.52MiB
panic: Refund counter below zero (gas: 15000 > refund: 8400)

**Comment by ericlee42** [comment]
Thanks for the feedback.

We are investigating this error, please use snapshot we provided first.

duplicated #37
