### ISSUE TITLE
After fresh sync finished, get `handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"`

### ISSUE THREAD

**Issue by yorickdowne** [MetisProtocol/metis-replica-node#40]
### What Git revision / release tag are you using?

20240316

### What is your hardware specification?

6 CPU, 64 GiB RAM, 2 TB NVMe

### What Docker version are you using?

25.0.4

### What Linux distribution are you using?

Debian 12

### Describe what the problem is?

Fresh-synced with `GCMODE=archive` an l2geth-5. It finished sync and appeared to be following head, but then logged an error `handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"` and seemingly did not recover. Larger log snippet below.

### If applicable, what are the logs from the server around the occurence of the problem?

l2geth-1  | INFO [03-16|16:59:40.765] Imported new chain segment               blocks=1    txs=1  mgas=0.381 elapsed=2.309ms   mgasps=164.891 number=15291598 hash=2130de…422a62 dirty=
0.00B
l2geth-1  | INFO [03-16|16:59:40.765] handle blocks inerted of fetcher or downloader len=1
l2geth-1  | INFO [03-16|16:59:40.765] start to applyTransaction                tx=0x4ca4f8fcbbe3abf5024567d2c8198fe792a4e0a2d19d413c3d54f2afb49a81f8
l2geth-1  | INFO [03-16|16:59:40.765] applyTransaction                         tx=0x4ca4f8fcbbe3abf5024567d2c8198fe792a4e0a2d19d413c3d54f2afb49a81f8 fromLocal=false
l2geth-1  | INFO [03-16|16:59:40.765] sync from other node                     index=15291597 hash=0x4ca4f8fcbbe3abf5024567d2c8198fe792a4e0a2d19d413c3d54f2afb49a81f8
l2geth-1  | INFO [03-16|16:59:40.765] sync from other node applyTransactionToTip finish current latest=15291597
l2geth-1  | INFO [03-16|16:59:40.812] handle blocks inerted of fetcher or downloader len=2
l2geth-1  | INFO [03-16|16:59:40.812] start to applyTransaction                tx=0x66564f1cb0d46bea0ba03c31f686f9e29ccdd83bd1891ab0f0d4f0f13a55ef84
l2geth-1  | INFO [03-16|16:59:40.812] applyTransaction                         tx=0x66564f1cb0d46bea0ba03c31f686f9e29ccdd83bd1891ab0f0d4f0f13a55ef84 fromLocal=false
l2geth-1  | INFO [03-16|16:59:40.812] start to applyTransaction                tx=0x4ca4f8fcbbe3abf5024567d2c8198fe792a4e0a2d19d413c3d54f2afb49a81f8
l2geth-1  | INFO [03-16|16:59:40.812] applyTransaction                         tx=0x4ca4f8fcbbe3abf5024567d2c8198fe792a4e0a2d19d413c3d54f2afb49a81f8 fromLocal=false
l2geth-1  | INFO [03-16|16:59:44.709] Imported new chain segment               blocks=1    txs=1  mgas=0.053 elapsed=1.003ms   mgasps=52.445  number=15291599 hash=a3286b…74b05b dirty=
0.00B
l2geth-1  | INFO [03-16|16:59:44.709] handle blocks inerted of fetcher or downloader len=1
l2geth-1  | INFO [03-16|16:59:44.709] start to applyTransaction                tx=0xe79d09361a5d156d8fe7c79d2eea13ecabaa6d1065106b27199c7e7f751a7e15
l2geth-1  | INFO [03-16|16:59:44.709] applyTransaction                         tx=0xe79d09361a5d156d8fe7c79d2eea13ecabaa6d1065106b27199c7e7f751a7e15 fromLocal=false
l2geth-1  | INFO [03-16|16:59:44.710] sync from other node                     index=15291598 hash=0xe79d09361a5d156d8fe7c79d2eea13ecabaa6d1065106b27199c7e7f751a7e15
l2geth-1  | INFO [03-16|16:59:44.710] sync from other node applyTransactionToTip finish current latest=15291598
l2geth-1  | INFO [03-16|16:59:46.720] Imported new chain segment               blocks=1    txs=1  mgas=0.384 elapsed=2.626ms   mgasps=146.120 number=15291600 hash=622e35…4a841b dirty=
0.00B
l2geth-1  | INFO [03-16|16:59:46.720] handle blocks inerted of fetcher or downloader len=1
l2geth-1  | INFO [03-16|16:59:46.720] start to applyTransaction                tx=0x64c0b498526e7f36162d0a1a65f2b5aab81cdc7083436cef81ddbe7fbea14552
l2geth-1  | INFO [03-16|16:59:46.720] applyTransaction                         tx=0x64c0b498526e7f36162d0a1a65f2b5aab81cdc7083436cef81ddbe7fbea14552 fromLocal=false
l2geth-1  | INFO [03-16|16:59:46.721] sync from other node                     index=15291599 hash=0x64c0b498526e7f36162d0a1a65f2b5aab81cdc7083436cef81ddbe7fbea14552
l2geth-1  | INFO [03-16|16:59:46.721] sync from other node applyTransactionToTip finish current latest=15291599
l2geth-1  | INFO [03-16|16:59:46.902] Imported new chain segment               blocks=2    txs=2  mgas=0.181 elapsed=2.719ms   mgasps=66.390  number=15291602 hash=6628f1…e3fbd3 dirty=0.00B
l2geth-1  | INFO [03-16|16:59:46.902] handle blocks inerted of fetcher or downloader len=2
l2geth-1  | INFO [03-16|16:59:46.902] start to applyTransaction                tx=0x4745d8bb69ff063c9e242d92bcf69c7536e193afa5b24a78319fc3f933d2d90d
l2geth-1  | INFO [03-16|16:59:46.902] applyTransaction                         tx=0x4745d8bb69ff063c9e242d92bcf69c7536e193afa5b24a78319fc3f933d2d90d fromLocal=false
l2geth-1  | INFO [03-16|16:59:46.902] sync from other node                     index=15291600 hash=0x4745d8bb69ff063c9e242d92bcf69c7536e193afa5b24a78319fc3f933d2d90d
l2geth-1  | INFO [03-16|16:59:46.902] sync from other node applyTransactionToTip finish current latest=15291600
l2geth-1  | INFO [03-16|16:59:46.902] start to applyTransaction                tx=0xe84f36ba3c15242df4a326169b345c9674cf1694c54e3481683c1bc85ddf9808
l2geth-1  | INFO [03-16|16:59:46.902] applyTransaction                         tx=0xe84f36ba3c15242df4a326169b345c9674cf1694c54e3481683c1bc85ddf9808 fromLocal=false
l2geth-1  | INFO [03-16|16:59:46.902] sync from other node                     index=15291601 hash=0xe84f36ba3c15242df4a326169b345c9674cf1694c54e3481683c1bc85ddf9808
l2geth-1  | INFO [03-16|16:59:46.902] sync from other node applyTransactionToTip finish current latest=15291601
l2geth-1  | ERROR[03-16|16:59:50.670] handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
l2geth-1  | ERROR[03-16|16:59:51.480] handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
l2geth-1  | WARN [03-16|16:59:51.480] Synchronisation failed, retrying         err="element not found"
l2geth-1  | INFO [03-16|16:59:53.407] handle blocks inerted of fetcher or downloader len=1
l2geth-1  | INFO [03-16|16:59:53.408] start to applyTransaction                tx=0xe84f36ba3c15242df4a326169b345c9674cf1694c54e3481683c1bc85ddf9808
l2geth-1  | INFO [03-16|16:59:53.408] applyTransaction                         tx=0xe84f36ba3c15242df4a326169b345c9674cf1694c54e3481683c1bc85ddf9808 fromLocal=false
l2geth-1  | ERROR[03-16|16:59:53.637] handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
l2geth-1  | WARN [03-16|16:59:53.637] Synchronisation failed, retrying         err="element not found"
l2geth-1  | ERROR[03-16|16:59:59.925] handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
l2geth-1  | WARN [03-16|16:59:59.925] Synchronisation failed, retrying         err="element not found"
l2geth-1  | ERROR[03-16|17:00:10.022] handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
l2geth-1  | WARN [03-16|17:00:10.022] Synchronisation failed, retrying         err="element not found"
l2geth-1  | ERROR[03-16|17:00:19.849] handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
l2geth-1  | WARN [03-16|17:00:19.849] Synchronisation failed, retrying         err="element not found"
l2geth-1  | ERROR[03-16|17:00:20.886] handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
l2geth-1  | WARN [03-16|17:00:20.886] Synchronisation failed, retrying         err="element not found"
l2geth-1  | INFO [03-16|17:00:21.656] Deep froze chain segment                 blocks=10   elapsed=54.329ms  number=15201601 hash=bb13b5…aee86a
l2geth-1  | ERROR[03-16|17:00:24.785] handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
l2geth-1  | WARN [03-16|17:00:24.785] Synchronisation failed, retrying         err="element not found"
l2geth-1  | ERROR[03-16|17:00:33.029] handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
l2geth-1  | WARN [03-16|17:00:33.029] Synchronisation failed, retrying         err="element not found"
l2geth-1  | ERROR[03-16|17:00:51.649] handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
l2geth-1  | WARN [03-16|17:00:51.649] Synchronisation failed, retrying         err="element not found"
l2geth-1  | ERROR[03-16|17:00:51.720] handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
l2geth-1  | WARN [03-16|17:00:51.720] Synchronisation failed, retrying         err="element not found"
l2geth-1  | ERROR[03-16|17:01:11.348] handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
l2geth-1  | WARN [03-16|17:01:11.348] Synchronisation failed, retrying         err="element not found"

**Comment by mookim-eth** [comment]
same issue, repeated `handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"` , but i didnt enable GCMODE=archive

```
ERROR[03-16|19:57:15.273] handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
WARN [03-16|19:57:15.273] Synchronisation failed, retrying         err="element not found"
ERROR[03-16|19:57:17.442] handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
WARN [03-16|19:57:17.442] Synchronisation failed, retrying         err="element not found"
ERROR[03-16|19:57:24.505] Canonical hash missing, can't freeze     number=2222096
INFO [03-16|19:57:24.505] Deep froze chain segment                 blocks=0    elapsed=5.287ms   number=2222095
ERROR[03-16|19:57:31.314] handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
WARN [03-16|19:57:31.314] Synchronisation failed, retrying         err="element not found"
```

then restarting the geth container gives this and exited:

```
INFO [03-16|19:58:24.844] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=512.00MiB handles=524288
INFO [03-16|19:58:24.896] Opened ancient database                  database=/root/.ethereum/geth/chaindata/ancient
Fatal: Error starting protocol stack: gap (#2222096) in the chain between ancients and leveldb
Fatal: Error starting protocol stack: gap (#2222096) in the chain between ancients and leveldb
```

**Comment by ericlee42** [comment]
Hi, It's due to your l1dtl is not synced.

You can use the latest dtl snapshot and try again.
