### ISSUE TITLE
Can't launch DTL

### ISSUE THREAD

**Issue by yzhou61** [MetisProtocol/metis-replica-node#41]
### What Git revision / release tag are you using?

68e95e3b78a87fe4fcccd70dd26e6b3ced7d4ace

### What is your hardware specification?

AWS C6.4x

### What Docker version are you using?

25.0.2

### What Linux distribution are you using?

Ubuntu 20.04

### Describe what the problem is?

l1dtl_1   | {"level":30,"time":1710513326257,"msg":"Service L1_Data_Transport_Service is starting..."}
l1dtl_1   | {"level":30,"time":1710513326258,"msg":"Service L1_Data_Transport_Service is initializing..."}
l1dtl_1   | {"level":30,"time":1710513326258,"msg":"Initializing L1 Data Transport Service..."}
l1dtl_1   | {"level":30,"time":1710513326268,"msg":"Service L1_Transport_Server is initializing..."}
l1dtl_1   | {"level":30,"time":1710513326272,"defaultBackend":"l1","l1GasPriceBackend":"l1","msg":"HTTP Server Options"}
l1dtl_1   | {"level":40,"time":1710513326272,"msg":"HTTP Server L1 RPC Provider not initialized"}
l1dtl_1   | {"level":30,"time":1710513326273,"url":"https://andromeda.metis.io","msg":"HTTP Server L2 RPC Provider initialized"}
l1dtl_1   | {"level":30,"time":1710513326273,"msg":"Service L1_Transport_Server has initialized."}
l1dtl_1   | {"level":30,"time":1710513326273,"msg":"Service L1_Ingestion_Service is initializing..."}
l1dtl_1   | {"level":30,"time":1710513326309,"addressManager":"0x918778e825747a892b17C66fe7D24C618262867d","msg":"Using AddressManager"}
l1dtl_1   | Well, that's that. We ran into a fatal error. Here's the dump. Goodbye!
l1dtl_1   | TypeError: Cannot read properties of null (reading 'getCode')
l1dtl_1   |     at L1IngestionService._init (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:152:49)
l1dtl_1   |     at L1IngestionService.init (/opt/optimism/packages/common-ts/src/base-service.ts:55:5)
l1dtl_1   |     at L1DataTransportService._init (/opt/optimism/packages/data-transport-layer/src/services/main/service.ts:138:7)
l1dtl_1   |     at L1DataTransportService.init (/opt/optimism/packages/common-ts/src/base-service.ts:55:5)
l1dtl_1   |     at L1DataTransportService.start (/opt/optimism/packages/common-ts/src/base-service.ts:68:5)
l1dtl_1   |     at <anonymous> (/opt/optimism/packages/data-transport-layer/src/services/run.ts:78:5)

**Comment by ericlee42** [comment]
You're not using correct eth rpc.

refer to 

https://github.com/MetisProtocol/metis-replica-node?tab=readme-ov-file#update-configuration

and check if the config is correct
