### ISSUE TITLE
no contract code at given address 

### ISSUE THREAD

**Issue by dg123lzk** [MetisProtocol/metis-replica-node#43]
正常运行的节点，三天前突然报错：no contract code at given address

**Comment by dg123lzk** [comment]
Three days ago, the node that is running normally suddenly reported an error: no contract code at given address

**Comment by aiden069** [comment]
> no contract code at given address

Could you upload the detail logs here? Thanks.

**Comment by dg123lzk** [comment]
ERROR[03-21|10:32:52.212] Got error waiting for transaction to be added to chain msg="nonce too high"
ERROR[03-21|10:32:52.212] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: nonce too high"
INFO [03-21|10:32:52.409] Syncing transaction range                start=15239253 end=15556044 backend=l2
ERROR[03-21|10:32:52.411] Problem committing transaction           msg="nonce too high"
ERROR[03-21|10:32:52.411] Got error waiting for transaction to be added to chain msg="nonce too high"
ERROR[03-21|10:32:52.411] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: nonce too high"
INFO [03-21|10:32:52.610] Syncing transaction range                start=15239253 end=15556044 backend=l2
ERROR[03-21|10:32:52.612] Problem committing transaction           msg="nonce too high"
ERROR[03-21|10:32:52.612] Got error waiting for transaction to be added to chain msg="nonce too high"
ERROR[03-21|10:32:52.612] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: nonce too high"
INFO [03-21|10:32:52.810] Syncing transaction range                start=15239253 end=15556044 backend=l2
ERROR[03-21|10:32:52.812] Problem committing transaction           msg="nonce too high"
ERROR[03-21|10:32:52.812] Got error waiting for transaction to be added to chain msg="nonce too high"
ERROR[03-21|10:32:52.812] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: nonce too high"

**Comment by ericlee42** [comment]
You're using incorrect configuration.

the backend configuration should be L1 instead of L2.

please refer to README to upgrade your node.
