### ISSUE TITLE
l2geth errors, does not sync

### ISSUE THREAD

**Issue by letsbangout** [MetisProtocol/metis-replica-node#46]
I upgraded a node which was probably quite a bit old.  I don't know version numbers.  Per the docs I saved my l2geth directory, and I assumed that once l1dtl caught up, l2geth would come alive.  I was right, l2geth seemed dormant until l1dtl reached tip.  It acted like it was going to sync, and reached as new as 2 days behind worth of data, like so:

INFO [04-02|18:17:43.305] Imported new chain segment               blocks=1077  txs=1077 mgas=185.881 elapsed=8.006s    mgasps=23.217 number=15988185 hash=a7c232…49ad4d age=2d18h45m dirty=255.66MiB
INFO [04-02|18:17:50.201] Imported new chain segment               blocks=971   txs=971  mgas=162.019 elapsed=6.896s    mgasps=23.493 number=15989156 hash=9978be…844856 age=2d17h22m dirty=255.42MiB

but at some point after that, which I do not have captured in my logs, it aborted the synchronization and began throwing errors like so:

ERROR[04-03|06:12:26.176] missing trie node:leveldb: not found
ERROR[04-03|06:12:26.176] goroutine 2532608 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/ethereum-optimism/optimism/l2geth/trie.(*Database).node(0xc0000b2000, {0x23, 0x70, 0x0, 0x50, 0x7, 0xfc, 0x34, 0x1d, 0x5f, ...})
        /l2geth/trie/database.go:390 +0x28a
github.com/ethereum-optimism/optimism/l2geth/trie.(*Trie).resolveHash(0xc030aad770?, {0xc046379b88?, 0xc03f544f80?, 0xfbd980?}, {0x0, 0x0, 0x0})
        /l2geth/trie/trie.go:392 +0xda
github.com/ethereum-optimism/optimism/l2geth/trie.New({0x23, 0x70, 0x0, 0x50, 0x7, 0xfc, 0x34, 0x1d, 0x5f, 0xbe, ...}, ...)
        /l2geth/trie/trie.go:71 +0xea
github.com/ethereum-optimism/optimism/l2geth/trie.NewSecure({0x23, 0x70, 0x0, 0x50, 0x7, 0xfc, 0x34, 0x1d, 0x5f, 0xbe, ...}, ...)
        /l2geth/trie/secure_trie.go:58 +0x2f
github.com/ethereum-optimism/optimism/l2geth/core/state.(*cachingDB).OpenTrie(0xc0002fa1b0?, {0x23, 0x70, 0x0, 0x50, 0x7, 0xfc, 0x34, 0x1d, 0x5f, ...})
        /l2geth/core/state/database.go:124 +0x29
github.com/ethereum-optimism/optimism/l2geth/core.(*BlockChain).HasState(...)
        /l2geth/core/blockchain.go:731
github.com/ethereum-optimism/optimism/l2geth/core.(*BlockChain).insertSideChain(0xc000f80000, 0x10ce9d2?, 0xc04637e3f0)
        /l2geth/core/blockchain.go:2288 +0x129d
github.com/ethereum-optimism/optimism/l2geth/core.(*BlockChain).insertChainWithFuncAndCh(0xc000f80000, {0xc033da5a80?, 0x2, 0x2}, 0x1, 0xc03fd6b140?, 0xc03fd6b1a0?, {0xee28a0?, 0xc02c1abd00})
        /l2geth/core/blockchain.go:1976 +0xf5d
created by github.com/ethereum-optimism/optimism/l2geth/core.(*BlockChain).InsertChainWithFunc in goroutine 2532914
        /l2geth/core/blockchain.go:1534 +0xb6d

The logs are full of such errors.

OS is Ubuntu 20.04 with the following docker images:

  l1dtl:
    image: ericlee42/metis:dtl-4
  l2geth:
    image: ericlee42/metis:l2geth-5

**Comment by ericlee42** [comment]
Are you using `GCMODE=full` ?

**Comment by ericlee42** [comment]
Hi, we have new release for it.

please use `metisdao/l2geth:v0.0.4` image and you meed to delete the data to use it.

**Comment by letsbangout** [comment]
Thanks, I have pulled the image and launched it with an empty data directory.

Is it possible to access a snapshot of l2geth data without an AWS instance?  Maybe there is a URL I can use?
